# Generated by Django 4.1 on 2022-08-23 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportedLang',
            fields=[
                ('lang', models.CharField(max_length=25, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.TextField(max_length=5000)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('is_private', models.BooleanField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.supportedlang')),
            ],
        ),
    ]
